### ISSUE TITLE
RuntimeError when static file changes

### ISSUE THREAD

**Issue by florimondmanca** [bocadilloproject/bocadillo#288]
**Expected behavior**

When an app is served with uvicorn (with static files), and a static file changes, a subsequent request should send the updated static file.

**Actual behavior**

Subsequent request fails with `RuntimeError: Response content shorter than Content-Length`.

**To Reproduce**

- Create static directory:

```
mkdir static
```

- App:

```python
# app.py
from bocadillo import App, configure
app = configure(App())
```

- Serve:

```bash
uvicorn app:app
```

- Add a static file:

```bash
echo "Hello" > static/hello.txt
```

- Access it:

```
curl http://localhost:8000/static/hello.txt
```

- Change it:

```bash
echo "Bye" > static/hello.txt
```

- Access it again, and the `RuntimeError` is raised.

**Screenshots/Traceback**

```
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/Users/Florimond/.pyenv/versions/3.7.2/lib/python3.7/site-packages/bocadillo/applications.py", line 242, in dispatch
    return await app(scope, receive, send)
TypeError: __call__() takes 3 positional arguments but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Florimond/.pyenv/versions/3.7.2/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 368, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/Florimond/.pyenv/versions/3.7.2/lib/python3.7/site-packages/bocadillo/applications.py", line 257, in __call__
    await self.asgi(scope, receive, send)
  File "/Users/Florimond/.pyenv/versions/3.7.2/lib/python3.7/site-packages/starlette/middleware/trustedhost.py", line 34, in __call__
    await self.app(scope, receive, send)
  File "/Users/Florimond/.pyenv/versions/3.7.2/lib/python3.7/site-packages/bocadillo/applications.py", line 245, in dispatch
    return await app(scope, receive, send)
  File "/Users/Florimond/.pyenv/versions/3.7.2/lib/python3.7/site-packages/starlette/middleware/wsgi.py", line 62, in __call__
    await responder(receive, send)
  File "/Users/Florimond/.pyenv/versions/3.7.2/lib/python3.7/site-packages/starlette/middleware/wsgi.py", line 90, in __call__
    await asyncio.wait_for(sender, None)
  File "/Users/Florimond/.pyenv/versions/3.7.2/lib/python3.7/asyncio/tasks.py", line 388, in wait_for
    return await fut
  File "/Users/Florimond/.pyenv/versions/3.7.2/lib/python3.7/site-packages/starlette/middleware/wsgi.py", line 105, in sender
    await send(message)
  File "/Users/Florimond/.pyenv/versions/3.7.2/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 497, in send
    raise RuntimeError("Response content shorter than Content-Length")
RuntimeError: Response content shorter than Content-Length
```

**Possible solutions**

**Specs**
- OS + Version: macOS Mojave
- Python Version: 3.7.2
- Bocadillo Version: 0.15.1

**Additional context**

First discovered by @DariusMiu in #272

**Comment by florimondmanca** [comment]
We already had an issue with static file refresh: https://github.com/bocadilloproject/bocadillo/issues/179

At the time, the issue was resolved by setting `autorefresh=True` on `WhiteNoise` when running with `debug=True`. There is no debug mode anymore, so `autorefresh` is always `False`.

The following solves the bug:

```python
app = configure(App(), static_config={"autorefresh": True})
```

**Comment by florimondmanca** [comment]
So, possible solutions:

1. Document the above workaround when expecting static files to refresh, e.g. when running with hot reload
2. Reintroduce an optional `DEBUG` setting, which sets `autorefresh=True`.
3. Always set `autorefresh=True`. This would reduce performance, because WhiteNoise will check the file system before responding (according to the docs).

**Comment by aligoren** [comment]
If you just want to watch static dir you can also use --reload-dir <YOUR_DIR_NAME> flag on uvicorn. They explained like below

> Specify which directories to watch for python file changes. May be used multiple times. If unused, then by default all directories in sys.path will be watched.

Actually the hypercoon uses --reload flag too.
